// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Common.proto

package com.game.protobuf.common;

public final class CommonProto {
  private CommonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PBPingReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 clientTick = 1;
    boolean hasClientTick();
    long getClientTick();
    
    // required int32 delay = 2;
    boolean hasDelay();
    int getDelay();
  }
  public static final class PBPingReq extends
      com.google.protobuf.GeneratedMessage
      implements PBPingReqOrBuilder {
    // Use PBPingReq.newBuilder() to construct.
    private PBPingReq(Builder builder) {
      super(builder);
    }
    private PBPingReq(boolean noInit) {}
    
    private static final PBPingReq defaultInstance;
    public static PBPingReq getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBPingReq getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.protobuf.common.CommonProto.internal_static_PBPingReq_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.protobuf.common.CommonProto.internal_static_PBPingReq_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 clientTick = 1;
    public static final int CLIENTTICK_FIELD_NUMBER = 1;
    private long clientTick_;
    public boolean hasClientTick() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getClientTick() {
      return clientTick_;
    }
    
    // required int32 delay = 2;
    public static final int DELAY_FIELD_NUMBER = 2;
    private int delay_;
    public boolean hasDelay() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getDelay() {
      return delay_;
    }
    
    private void initFields() {
      clientTick_ = 0L;
      delay_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasClientTick()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDelay()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, clientTick_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, delay_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, clientTick_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, delay_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.game.protobuf.common.CommonProto.PBPingReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game.protobuf.common.CommonProto.PBPingReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game.protobuf.common.CommonProto.PBPingReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game.protobuf.common.CommonProto.PBPingReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game.protobuf.common.CommonProto.PBPingReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game.protobuf.common.CommonProto.PBPingReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.game.protobuf.common.CommonProto.PBPingReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game.protobuf.common.CommonProto.PBPingReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game.protobuf.common.CommonProto.PBPingReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game.protobuf.common.CommonProto.PBPingReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.protobuf.common.CommonProto.PBPingReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.protobuf.common.CommonProto.PBPingReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.protobuf.common.CommonProto.internal_static_PBPingReq_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.protobuf.common.CommonProto.internal_static_PBPingReq_fieldAccessorTable;
      }
      
      // Construct using com.game.protobuf.common.CommonProto.PBPingReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        clientTick_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        delay_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.protobuf.common.CommonProto.PBPingReq.getDescriptor();
      }
      
      public com.game.protobuf.common.CommonProto.PBPingReq getDefaultInstanceForType() {
        return com.game.protobuf.common.CommonProto.PBPingReq.getDefaultInstance();
      }
      
      public com.game.protobuf.common.CommonProto.PBPingReq build() {
        com.game.protobuf.common.CommonProto.PBPingReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.game.protobuf.common.CommonProto.PBPingReq buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.game.protobuf.common.CommonProto.PBPingReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.game.protobuf.common.CommonProto.PBPingReq buildPartial() {
        com.game.protobuf.common.CommonProto.PBPingReq result = new com.game.protobuf.common.CommonProto.PBPingReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clientTick_ = clientTick_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.delay_ = delay_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.protobuf.common.CommonProto.PBPingReq) {
          return mergeFrom((com.game.protobuf.common.CommonProto.PBPingReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.game.protobuf.common.CommonProto.PBPingReq other) {
        if (other == com.game.protobuf.common.CommonProto.PBPingReq.getDefaultInstance()) return this;
        if (other.hasClientTick()) {
          setClientTick(other.getClientTick());
        }
        if (other.hasDelay()) {
          setDelay(other.getDelay());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasClientTick()) {
          
          return false;
        }
        if (!hasDelay()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              clientTick_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              delay_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 clientTick = 1;
      private long clientTick_ ;
      public boolean hasClientTick() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getClientTick() {
        return clientTick_;
      }
      public Builder setClientTick(long value) {
        bitField0_ |= 0x00000001;
        clientTick_ = value;
        onChanged();
        return this;
      }
      public Builder clearClientTick() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientTick_ = 0L;
        onChanged();
        return this;
      }
      
      // required int32 delay = 2;
      private int delay_ ;
      public boolean hasDelay() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getDelay() {
        return delay_;
      }
      public Builder setDelay(int value) {
        bitField0_ |= 0x00000002;
        delay_ = value;
        onChanged();
        return this;
      }
      public Builder clearDelay() {
        bitField0_ = (bitField0_ & ~0x00000002);
        delay_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:PBPingReq)
    }
    
    static {
      defaultInstance = new PBPingReq(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PBPingReq)
  }
  
  public interface PBPingRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 clientTick = 1;
    boolean hasClientTick();
    long getClientTick();
    
    // required int64 serverTick = 2;
    boolean hasServerTick();
    long getServerTick();
  }
  public static final class PBPingResp extends
      com.google.protobuf.GeneratedMessage
      implements PBPingRespOrBuilder {
    // Use PBPingResp.newBuilder() to construct.
    private PBPingResp(Builder builder) {
      super(builder);
    }
    private PBPingResp(boolean noInit) {}
    
    private static final PBPingResp defaultInstance;
    public static PBPingResp getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBPingResp getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.protobuf.common.CommonProto.internal_static_PBPingResp_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.protobuf.common.CommonProto.internal_static_PBPingResp_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 clientTick = 1;
    public static final int CLIENTTICK_FIELD_NUMBER = 1;
    private long clientTick_;
    public boolean hasClientTick() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getClientTick() {
      return clientTick_;
    }
    
    // required int64 serverTick = 2;
    public static final int SERVERTICK_FIELD_NUMBER = 2;
    private long serverTick_;
    public boolean hasServerTick() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getServerTick() {
      return serverTick_;
    }
    
    private void initFields() {
      clientTick_ = 0L;
      serverTick_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasClientTick()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerTick()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, clientTick_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, serverTick_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, clientTick_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, serverTick_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.game.protobuf.common.CommonProto.PBPingResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game.protobuf.common.CommonProto.PBPingResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game.protobuf.common.CommonProto.PBPingResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game.protobuf.common.CommonProto.PBPingResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game.protobuf.common.CommonProto.PBPingResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game.protobuf.common.CommonProto.PBPingResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.game.protobuf.common.CommonProto.PBPingResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game.protobuf.common.CommonProto.PBPingResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game.protobuf.common.CommonProto.PBPingResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game.protobuf.common.CommonProto.PBPingResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.protobuf.common.CommonProto.PBPingResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.protobuf.common.CommonProto.PBPingRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.protobuf.common.CommonProto.internal_static_PBPingResp_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.protobuf.common.CommonProto.internal_static_PBPingResp_fieldAccessorTable;
      }
      
      // Construct using com.game.protobuf.common.CommonProto.PBPingResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        clientTick_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        serverTick_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.protobuf.common.CommonProto.PBPingResp.getDescriptor();
      }
      
      public com.game.protobuf.common.CommonProto.PBPingResp getDefaultInstanceForType() {
        return com.game.protobuf.common.CommonProto.PBPingResp.getDefaultInstance();
      }
      
      public com.game.protobuf.common.CommonProto.PBPingResp build() {
        com.game.protobuf.common.CommonProto.PBPingResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.game.protobuf.common.CommonProto.PBPingResp buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.game.protobuf.common.CommonProto.PBPingResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.game.protobuf.common.CommonProto.PBPingResp buildPartial() {
        com.game.protobuf.common.CommonProto.PBPingResp result = new com.game.protobuf.common.CommonProto.PBPingResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clientTick_ = clientTick_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.serverTick_ = serverTick_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.protobuf.common.CommonProto.PBPingResp) {
          return mergeFrom((com.game.protobuf.common.CommonProto.PBPingResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.game.protobuf.common.CommonProto.PBPingResp other) {
        if (other == com.game.protobuf.common.CommonProto.PBPingResp.getDefaultInstance()) return this;
        if (other.hasClientTick()) {
          setClientTick(other.getClientTick());
        }
        if (other.hasServerTick()) {
          setServerTick(other.getServerTick());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasClientTick()) {
          
          return false;
        }
        if (!hasServerTick()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              clientTick_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              serverTick_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 clientTick = 1;
      private long clientTick_ ;
      public boolean hasClientTick() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getClientTick() {
        return clientTick_;
      }
      public Builder setClientTick(long value) {
        bitField0_ |= 0x00000001;
        clientTick_ = value;
        onChanged();
        return this;
      }
      public Builder clearClientTick() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientTick_ = 0L;
        onChanged();
        return this;
      }
      
      // required int64 serverTick = 2;
      private long serverTick_ ;
      public boolean hasServerTick() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getServerTick() {
        return serverTick_;
      }
      public Builder setServerTick(long value) {
        bitField0_ |= 0x00000002;
        serverTick_ = value;
        onChanged();
        return this;
      }
      public Builder clearServerTick() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serverTick_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:PBPingResp)
    }
    
    static {
      defaultInstance = new PBPingResp(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PBPingResp)
  }
  
  public interface PBTipMsgRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 type = 1;
    boolean hasType();
    int getType();
    
    // required int32 tipMsgCode = 2;
    boolean hasTipMsgCode();
    int getTipMsgCode();
    
    // repeated string args = 3;
    java.util.List<String> getArgsList();
    int getArgsCount();
    String getArgs(int index);
  }
  public static final class PBTipMsgResp extends
      com.google.protobuf.GeneratedMessage
      implements PBTipMsgRespOrBuilder {
    // Use PBTipMsgResp.newBuilder() to construct.
    private PBTipMsgResp(Builder builder) {
      super(builder);
    }
    private PBTipMsgResp(boolean noInit) {}
    
    private static final PBTipMsgResp defaultInstance;
    public static PBTipMsgResp getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBTipMsgResp getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.protobuf.common.CommonProto.internal_static_PBTipMsgResp_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.protobuf.common.CommonProto.internal_static_PBTipMsgResp_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getType() {
      return type_;
    }
    
    // required int32 tipMsgCode = 2;
    public static final int TIPMSGCODE_FIELD_NUMBER = 2;
    private int tipMsgCode_;
    public boolean hasTipMsgCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getTipMsgCode() {
      return tipMsgCode_;
    }
    
    // repeated string args = 3;
    public static final int ARGS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList args_;
    public java.util.List<String>
        getArgsList() {
      return args_;
    }
    public int getArgsCount() {
      return args_.size();
    }
    public String getArgs(int index) {
      return args_.get(index);
    }
    
    private void initFields() {
      type_ = 0;
      tipMsgCode_ = 0;
      args_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTipMsgCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, tipMsgCode_);
      }
      for (int i = 0; i < args_.size(); i++) {
        output.writeBytes(3, args_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, tipMsgCode_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < args_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(args_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getArgsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.game.protobuf.common.CommonProto.PBTipMsgResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game.protobuf.common.CommonProto.PBTipMsgResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game.protobuf.common.CommonProto.PBTipMsgResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game.protobuf.common.CommonProto.PBTipMsgResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game.protobuf.common.CommonProto.PBTipMsgResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game.protobuf.common.CommonProto.PBTipMsgResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.game.protobuf.common.CommonProto.PBTipMsgResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game.protobuf.common.CommonProto.PBTipMsgResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game.protobuf.common.CommonProto.PBTipMsgResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game.protobuf.common.CommonProto.PBTipMsgResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.protobuf.common.CommonProto.PBTipMsgResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.protobuf.common.CommonProto.PBTipMsgRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.protobuf.common.CommonProto.internal_static_PBTipMsgResp_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.protobuf.common.CommonProto.internal_static_PBTipMsgResp_fieldAccessorTable;
      }
      
      // Construct using com.game.protobuf.common.CommonProto.PBTipMsgResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        tipMsgCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        args_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.protobuf.common.CommonProto.PBTipMsgResp.getDescriptor();
      }
      
      public com.game.protobuf.common.CommonProto.PBTipMsgResp getDefaultInstanceForType() {
        return com.game.protobuf.common.CommonProto.PBTipMsgResp.getDefaultInstance();
      }
      
      public com.game.protobuf.common.CommonProto.PBTipMsgResp build() {
        com.game.protobuf.common.CommonProto.PBTipMsgResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.game.protobuf.common.CommonProto.PBTipMsgResp buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.game.protobuf.common.CommonProto.PBTipMsgResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.game.protobuf.common.CommonProto.PBTipMsgResp buildPartial() {
        com.game.protobuf.common.CommonProto.PBTipMsgResp result = new com.game.protobuf.common.CommonProto.PBTipMsgResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.tipMsgCode_ = tipMsgCode_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          args_ = new com.google.protobuf.UnmodifiableLazyStringList(
              args_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.args_ = args_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.protobuf.common.CommonProto.PBTipMsgResp) {
          return mergeFrom((com.game.protobuf.common.CommonProto.PBTipMsgResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.game.protobuf.common.CommonProto.PBTipMsgResp other) {
        if (other == com.game.protobuf.common.CommonProto.PBTipMsgResp.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasTipMsgCode()) {
          setTipMsgCode(other.getTipMsgCode());
        }
        if (!other.args_.isEmpty()) {
          if (args_.isEmpty()) {
            args_ = other.args_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureArgsIsMutable();
            args_.addAll(other.args_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasTipMsgCode()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              tipMsgCode_ = input.readInt32();
              break;
            }
            case 26: {
              ensureArgsIsMutable();
              args_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 type = 1;
      private int type_ ;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getType() {
        return type_;
      }
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 tipMsgCode = 2;
      private int tipMsgCode_ ;
      public boolean hasTipMsgCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getTipMsgCode() {
        return tipMsgCode_;
      }
      public Builder setTipMsgCode(int value) {
        bitField0_ |= 0x00000002;
        tipMsgCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearTipMsgCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tipMsgCode_ = 0;
        onChanged();
        return this;
      }
      
      // repeated string args = 3;
      private com.google.protobuf.LazyStringList args_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureArgsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          args_ = new com.google.protobuf.LazyStringArrayList(args_);
          bitField0_ |= 0x00000004;
         }
      }
      public java.util.List<String>
          getArgsList() {
        return java.util.Collections.unmodifiableList(args_);
      }
      public int getArgsCount() {
        return args_.size();
      }
      public String getArgs(int index) {
        return args_.get(index);
      }
      public Builder setArgs(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArgsIsMutable();
        args_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addArgs(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArgsIsMutable();
        args_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllArgs(
          java.lang.Iterable<String> values) {
        ensureArgsIsMutable();
        super.addAll(values, args_);
        onChanged();
        return this;
      }
      public Builder clearArgs() {
        args_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      void addArgs(com.google.protobuf.ByteString value) {
        ensureArgsIsMutable();
        args_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:PBTipMsgResp)
    }
    
    static {
      defaultInstance = new PBTipMsgResp(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PBTipMsgResp)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PBPingReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PBPingReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PBPingResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PBPingResp_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PBTipMsgResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PBTipMsgResp_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022proto/Common.proto\".\n\tPBPingReq\022\022\n\ncli" +
      "entTick\030\001 \002(\003\022\r\n\005delay\030\002 \002(\005\"4\n\nPBPingRe" +
      "sp\022\022\n\nclientTick\030\001 \002(\003\022\022\n\nserverTick\030\002 \002" +
      "(\003\">\n\014PBTipMsgResp\022\014\n\004type\030\001 \002(\005\022\022\n\ntipM" +
      "sgCode\030\002 \002(\005\022\014\n\004args\030\003 \003(\tB\'\n\030com.game.p" +
      "rotobuf.commonB\013CommonProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PBPingReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PBPingReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PBPingReq_descriptor,
              new java.lang.String[] { "ClientTick", "Delay", },
              com.game.protobuf.common.CommonProto.PBPingReq.class,
              com.game.protobuf.common.CommonProto.PBPingReq.Builder.class);
          internal_static_PBPingResp_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_PBPingResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PBPingResp_descriptor,
              new java.lang.String[] { "ClientTick", "ServerTick", },
              com.game.protobuf.common.CommonProto.PBPingResp.class,
              com.game.protobuf.common.CommonProto.PBPingResp.Builder.class);
          internal_static_PBTipMsgResp_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_PBTipMsgResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PBTipMsgResp_descriptor,
              new java.lang.String[] { "Type", "TipMsgCode", "Args", },
              com.game.protobuf.common.CommonProto.PBTipMsgResp.class,
              com.game.protobuf.common.CommonProto.PBTipMsgResp.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
