//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: proto/Common.proto
namespace proto.Common
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBPingReq")]
  public partial class PBPingReq : global::ProtoBuf.IExtensible
  {
    public PBPingReq() {}
    
    private long _clientTick;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"clientTick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long clientTick
    {
      get { return _clientTick; }
      set { _clientTick = value; }
    }
    private int _delay;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"delay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int delay
    {
      get { return _delay; }
      set { _delay = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBPingResp")]
  public partial class PBPingResp : global::ProtoBuf.IExtensible
  {
    public PBPingResp() {}
    
    private long _clientTick;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"clientTick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long clientTick
    {
      get { return _clientTick; }
      set { _clientTick = value; }
    }
    private long _serverTick;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"serverTick", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long serverTick
    {
      get { return _serverTick; }
      set { _serverTick = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBTipMsgResp")]
  public partial class PBTipMsgResp : global::ProtoBuf.IExtensible
  {
    public PBTipMsgResp() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _tipMsgCode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"tipMsgCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tipMsgCode
    {
      get { return _tipMsgCode; }
      set { _tipMsgCode = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _args = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"args", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> args
    {
      get { return _args; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}