//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: proto/Fighting.proto
namespace proto.Fighting
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBLivingInfoBean")]
  public partial class PBLivingInfoBean : global::ProtoBuf.IExtensible
  {
    public PBLivingInfoBean() {}
    
    private int _phId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"phId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int phId
    {
      get { return _phId; }
      set { _phId = value; }
    }
    private int _phType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"phType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int phType
    {
      get { return _phType; }
      set { _phType = value; }
    }
    private PBPropValueBean _propValues;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"propValues", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PBPropValueBean propValues
    {
      get { return _propValues; }
      set { _propValues = value; }
    }
    private int _x;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _campType;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"campType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int campType
    {
      get { return _campType; }
      set { _campType = value; }
    }
    private int _templateId;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"templateId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int templateId
    {
      get { return _templateId; }
      set { _templateId = value; }
    }
    private int _moveDir;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"moveDir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int moveDir
    {
      get { return _moveDir; }
      set { _moveDir = value; }
    }
    private int _faceDir;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"faceDir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int faceDir
    {
      get { return _faceDir; }
      set { _faceDir = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _skillId = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> skillId
    {
      get { return _skillId; }
    }
  

    private string _name;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return _name != null; }
      set { if (value == (_name== null)) _name = value ? name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    

    private long? _playerId;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long playerId
    {
      get { return _playerId?? default(long); }
      set { _playerId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool playerIdSpecified
    {
      get { return _playerId != null; }
      set { if (value == (_playerId== null)) _playerId = value ? playerId : (long?)null; }
    }
    private bool ShouldSerializeplayerId() { return playerIdSpecified; }
    private void ResetplayerId() { playerIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBPropValueBean")]
  public partial class PBPropValueBean : global::ProtoBuf.IExtensible
  {
    public PBPropValueBean() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBGameLoadingResp")]
  public partial class PBGameLoadingResp : global::ProtoBuf.IExtensible
  {
    public PBGameLoadingResp() {}
    
    private int _loadingTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"loadingTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int loadingTime
    {
      get { return _loadingTime; }
      set { _loadingTime = value; }
    }
    private int _sceneId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sceneId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sceneId
    {
      get { return _sceneId; }
      set { _sceneId = value; }
    }
    private int _gameId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private long _playerId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }

    private bool? _firstInGame;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"firstInGame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool firstInGame
    {
      get { return _firstInGame?? default(bool); }
      set { _firstInGame = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool firstInGameSpecified
    {
      get { return _firstInGame != null; }
      set { if (value == (_firstInGame== null)) _firstInGame = value ? firstInGame : (bool?)null; }
    }
    private bool ShouldSerializefirstInGame() { return firstInGameSpecified; }
    private void ResetfirstInGame() { firstInGameSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<PBLivingInfoBean> _livingInfo = new global::System.Collections.Generic.List<PBLivingInfoBean>();
    [global::ProtoBuf.ProtoMember(6, Name=@"livingInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBLivingInfoBean> livingInfo
    {
      get { return _livingInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBLoadingProcessReq")]
  public partial class PBLoadingProcessReq : global::ProtoBuf.IExtensible
  {
    public PBLoadingProcessReq() {}
    
    private int _process;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"process", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int process
    {
      get { return _process; }
      set { _process = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBLoadingProcessResp")]
  public partial class PBLoadingProcessResp : global::ProtoBuf.IExtensible
  {
    public PBLoadingProcessResp() {}
    
    private long _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _process;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"process", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int process
    {
      get { return _process; }
      set { _process = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBGameStartResp")]
  public partial class PBGameStartResp : global::ProtoBuf.IExtensible
  {
    public PBGameStartResp() {}
    
    private int _playerReadyTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerReadyTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerReadyTime
    {
      get { return _playerReadyTime; }
      set { _playerReadyTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMoveReq")]
  public partial class PBMoveReq : global::ProtoBuf.IExtensible
  {
    public PBMoveReq() {}
    
    private int _startX;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"startX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int startX
    {
      get { return _startX; }
      set { _startX = value; }
    }
    private int _startY;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"startY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int startY
    {
      get { return _startY; }
      set { _startY = value; }
    }
    private int _endX;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"endX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int endX
    {
      get { return _endX; }
      set { _endX = value; }
    }
    private int _endY;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"endY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int endY
    {
      get { return _endY; }
      set { _endY = value; }
    }
    private long _startTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long startTime
    {
      get { return _startTime; }
      set { _startTime = value; }
    }
    private int _faceDir;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"faceDir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int faceDir
    {
      get { return _faceDir; }
      set { _faceDir = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMoveResp")]
  public partial class PBMoveResp : global::ProtoBuf.IExtensible
  {
    public PBMoveResp() {}
    
    private int _phId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"phId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int phId
    {
      get { return _phId; }
      set { _phId = value; }
    }
    private int _startX;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"startX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int startX
    {
      get { return _startX; }
      set { _startX = value; }
    }
    private int _startY;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"startY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int startY
    {
      get { return _startY; }
      set { _startY = value; }
    }
    private int _endX;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"endX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int endX
    {
      get { return _endX; }
      set { _endX = value; }
    }
    private int _endY;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"endY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int endY
    {
      get { return _endY; }
      set { _endY = value; }
    }
    private long _startTime;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long startTime
    {
      get { return _startTime; }
      set { _startTime = value; }
    }
    private int _faceDir;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"faceDir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int faceDir
    {
      get { return _faceDir; }
      set { _faceDir = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMoveStopReq")]
  public partial class PBMoveStopReq : global::ProtoBuf.IExtensible
  {
    public PBMoveStopReq() {}
    
    private int _stopX;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"stopX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stopX
    {
      get { return _stopX; }
      set { _stopX = value; }
    }
    private int _stopY;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"stopY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stopY
    {
      get { return _stopY; }
      set { _stopY = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMoveStopResp")]
  public partial class PBMoveStopResp : global::ProtoBuf.IExtensible
  {
    public PBMoveStopResp() {}
    
    private int _phId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"phId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int phId
    {
      get { return _phId; }
      set { _phId = value; }
    }
    private int _toX;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"toX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int toX
    {
      get { return _toX; }
      set { _toX = value; }
    }
    private int _toY;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"toY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int toY
    {
      get { return _toY; }
      set { _toY = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBPropValueUpdateResp")]
  public partial class PBPropValueUpdateResp : global::ProtoBuf.IExtensible
  {
    public PBPropValueUpdateResp() {}
    
    private int _phId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"phId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int phId
    {
      get { return _phId; }
      set { _phId = value; }
    }
    private readonly global::System.Collections.Generic.List<PBPropValueBean> _propValues = new global::System.Collections.Generic.List<PBPropValueBean>();
    [global::ProtoBuf.ProtoMember(2, Name=@"propValues", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBPropValueBean> propValues
    {
      get { return _propValues; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBMoveCurPointResp")]
  public partial class PBMoveCurPointResp : global::ProtoBuf.IExtensible
  {
    public PBMoveCurPointResp() {}
    
    private int _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _phID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"phID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int phID
    {
      get { return _phID; }
      set { _phID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}