// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Match.proto

package com.game.protobuf.match;

public final class MatchProto {
  private MatchProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PBStartMatchReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 heroId = 1;
    boolean hasHeroId();
    int getHeroId();
    
    // required int32 fightingType = 2;
    boolean hasFightingType();
    int getFightingType();
  }
  public static final class PBStartMatchReq extends
      com.google.protobuf.GeneratedMessage
      implements PBStartMatchReqOrBuilder {
    // Use PBStartMatchReq.newBuilder() to construct.
    private PBStartMatchReq(Builder builder) {
      super(builder);
    }
    private PBStartMatchReq(boolean noInit) {}
    
    private static final PBStartMatchReq defaultInstance;
    public static PBStartMatchReq getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBStartMatchReq getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.protobuf.match.MatchProto.internal_static_PBStartMatchReq_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.protobuf.match.MatchProto.internal_static_PBStartMatchReq_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 heroId = 1;
    public static final int HEROID_FIELD_NUMBER = 1;
    private int heroId_;
    public boolean hasHeroId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getHeroId() {
      return heroId_;
    }
    
    // required int32 fightingType = 2;
    public static final int FIGHTINGTYPE_FIELD_NUMBER = 2;
    private int fightingType_;
    public boolean hasFightingType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getFightingType() {
      return fightingType_;
    }
    
    private void initFields() {
      heroId_ = 0;
      fightingType_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasHeroId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFightingType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, heroId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, fightingType_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, heroId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, fightingType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.game.protobuf.match.MatchProto.PBStartMatchReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game.protobuf.match.MatchProto.PBStartMatchReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game.protobuf.match.MatchProto.PBStartMatchReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game.protobuf.match.MatchProto.PBStartMatchReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game.protobuf.match.MatchProto.PBStartMatchReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game.protobuf.match.MatchProto.PBStartMatchReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.game.protobuf.match.MatchProto.PBStartMatchReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game.protobuf.match.MatchProto.PBStartMatchReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game.protobuf.match.MatchProto.PBStartMatchReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game.protobuf.match.MatchProto.PBStartMatchReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.protobuf.match.MatchProto.PBStartMatchReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.protobuf.match.MatchProto.PBStartMatchReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.protobuf.match.MatchProto.internal_static_PBStartMatchReq_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.protobuf.match.MatchProto.internal_static_PBStartMatchReq_fieldAccessorTable;
      }
      
      // Construct using com.game.protobuf.match.MatchProto.PBStartMatchReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        heroId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        fightingType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.protobuf.match.MatchProto.PBStartMatchReq.getDescriptor();
      }
      
      public com.game.protobuf.match.MatchProto.PBStartMatchReq getDefaultInstanceForType() {
        return com.game.protobuf.match.MatchProto.PBStartMatchReq.getDefaultInstance();
      }
      
      public com.game.protobuf.match.MatchProto.PBStartMatchReq build() {
        com.game.protobuf.match.MatchProto.PBStartMatchReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.game.protobuf.match.MatchProto.PBStartMatchReq buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.game.protobuf.match.MatchProto.PBStartMatchReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.game.protobuf.match.MatchProto.PBStartMatchReq buildPartial() {
        com.game.protobuf.match.MatchProto.PBStartMatchReq result = new com.game.protobuf.match.MatchProto.PBStartMatchReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.heroId_ = heroId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fightingType_ = fightingType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.protobuf.match.MatchProto.PBStartMatchReq) {
          return mergeFrom((com.game.protobuf.match.MatchProto.PBStartMatchReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.game.protobuf.match.MatchProto.PBStartMatchReq other) {
        if (other == com.game.protobuf.match.MatchProto.PBStartMatchReq.getDefaultInstance()) return this;
        if (other.hasHeroId()) {
          setHeroId(other.getHeroId());
        }
        if (other.hasFightingType()) {
          setFightingType(other.getFightingType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasHeroId()) {
          
          return false;
        }
        if (!hasFightingType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              heroId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              fightingType_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 heroId = 1;
      private int heroId_ ;
      public boolean hasHeroId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getHeroId() {
        return heroId_;
      }
      public Builder setHeroId(int value) {
        bitField0_ |= 0x00000001;
        heroId_ = value;
        onChanged();
        return this;
      }
      public Builder clearHeroId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        heroId_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 fightingType = 2;
      private int fightingType_ ;
      public boolean hasFightingType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getFightingType() {
        return fightingType_;
      }
      public Builder setFightingType(int value) {
        bitField0_ |= 0x00000002;
        fightingType_ = value;
        onChanged();
        return this;
      }
      public Builder clearFightingType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fightingType_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:PBStartMatchReq)
    }
    
    static {
      defaultInstance = new PBStartMatchReq(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PBStartMatchReq)
  }
  
  public interface PBStartMatchRespOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 matchTime = 1;
    boolean hasMatchTime();
    int getMatchTime();
  }
  public static final class PBStartMatchResp extends
      com.google.protobuf.GeneratedMessage
      implements PBStartMatchRespOrBuilder {
    // Use PBStartMatchResp.newBuilder() to construct.
    private PBStartMatchResp(Builder builder) {
      super(builder);
    }
    private PBStartMatchResp(boolean noInit) {}
    
    private static final PBStartMatchResp defaultInstance;
    public static PBStartMatchResp getDefaultInstance() {
      return defaultInstance;
    }
    
    public PBStartMatchResp getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.protobuf.match.MatchProto.internal_static_PBStartMatchResp_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.protobuf.match.MatchProto.internal_static_PBStartMatchResp_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 matchTime = 1;
    public static final int MATCHTIME_FIELD_NUMBER = 1;
    private int matchTime_;
    public boolean hasMatchTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getMatchTime() {
      return matchTime_;
    }
    
    private void initFields() {
      matchTime_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMatchTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, matchTime_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, matchTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.game.protobuf.match.MatchProto.PBStartMatchResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game.protobuf.match.MatchProto.PBStartMatchResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game.protobuf.match.MatchProto.PBStartMatchResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.game.protobuf.match.MatchProto.PBStartMatchResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.game.protobuf.match.MatchProto.PBStartMatchResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game.protobuf.match.MatchProto.PBStartMatchResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.game.protobuf.match.MatchProto.PBStartMatchResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game.protobuf.match.MatchProto.PBStartMatchResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.game.protobuf.match.MatchProto.PBStartMatchResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.game.protobuf.match.MatchProto.PBStartMatchResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.game.protobuf.match.MatchProto.PBStartMatchResp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.game.protobuf.match.MatchProto.PBStartMatchRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.protobuf.match.MatchProto.internal_static_PBStartMatchResp_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.protobuf.match.MatchProto.internal_static_PBStartMatchResp_fieldAccessorTable;
      }
      
      // Construct using com.game.protobuf.match.MatchProto.PBStartMatchResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        matchTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.protobuf.match.MatchProto.PBStartMatchResp.getDescriptor();
      }
      
      public com.game.protobuf.match.MatchProto.PBStartMatchResp getDefaultInstanceForType() {
        return com.game.protobuf.match.MatchProto.PBStartMatchResp.getDefaultInstance();
      }
      
      public com.game.protobuf.match.MatchProto.PBStartMatchResp build() {
        com.game.protobuf.match.MatchProto.PBStartMatchResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.game.protobuf.match.MatchProto.PBStartMatchResp buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.game.protobuf.match.MatchProto.PBStartMatchResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.game.protobuf.match.MatchProto.PBStartMatchResp buildPartial() {
        com.game.protobuf.match.MatchProto.PBStartMatchResp result = new com.game.protobuf.match.MatchProto.PBStartMatchResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.matchTime_ = matchTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.protobuf.match.MatchProto.PBStartMatchResp) {
          return mergeFrom((com.game.protobuf.match.MatchProto.PBStartMatchResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.game.protobuf.match.MatchProto.PBStartMatchResp other) {
        if (other == com.game.protobuf.match.MatchProto.PBStartMatchResp.getDefaultInstance()) return this;
        if (other.hasMatchTime()) {
          setMatchTime(other.getMatchTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMatchTime()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              matchTime_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 matchTime = 1;
      private int matchTime_ ;
      public boolean hasMatchTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getMatchTime() {
        return matchTime_;
      }
      public Builder setMatchTime(int value) {
        bitField0_ |= 0x00000001;
        matchTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearMatchTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        matchTime_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:PBStartMatchResp)
    }
    
    static {
      defaultInstance = new PBStartMatchResp(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PBStartMatchResp)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PBStartMatchReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PBStartMatchReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PBStartMatchResp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PBStartMatchResp_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021proto/Match.proto\"7\n\017PBStartMatchReq\022\016" +
      "\n\006heroId\030\001 \002(\005\022\024\n\014fightingType\030\002 \002(\005\"%\n\020" +
      "PBStartMatchResp\022\021\n\tmatchTime\030\001 \002(\005B%\n\027c" +
      "om.game.protobuf.matchB\nMatchProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PBStartMatchReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PBStartMatchReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PBStartMatchReq_descriptor,
              new java.lang.String[] { "HeroId", "FightingType", },
              com.game.protobuf.match.MatchProto.PBStartMatchReq.class,
              com.game.protobuf.match.MatchProto.PBStartMatchReq.Builder.class);
          internal_static_PBStartMatchResp_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_PBStartMatchResp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PBStartMatchResp_descriptor,
              new java.lang.String[] { "MatchTime", },
              com.game.protobuf.match.MatchProto.PBStartMatchResp.class,
              com.game.protobuf.match.MatchProto.PBStartMatchResp.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
